BaseDir "/var/run/collectd"
Include "/etc/collectd/conf.d/*.conf"
PIDFile "/var/run/collectd.pid"
PluginDir "/usr/lib/collectd"
TypesDB "/usr/share/collectd/types.db"
Interval 15
ReadThreads 2

LoadPlugin cpu
<Plugin cpu>
	ReportByCpu true
	ReportByState false
</Plugin>

LoadPlugin cpufreq

LoadPlugin exec
<Plugin exec>
	Exec "nobody:nogroup" "/usr/libexec/collectd/sqm_collectd.sh" "eth0"
</Plugin>

LoadPlugin interface
<Plugin interface>
	Interface "br-guest"
	Interface "br-lan"
	Interface "br-wan"
	Interface "br-work"
	Interface "lan1"
	Interface "lan2"
	Interface "lan3"
	Interface "lan4"
	Interface "wgclient"
	Interface "wgserver"
</Plugin>

LoadPlugin iwinfo
<Plugin iwinfo>
	Interface "guestiso"
	Interface "GuestU5"
	Interface "watchlan"
	Interface "wlan01"
	Interface "wlan02"
	Interface "workiso"
	Interface "workiso24"
</Plugin>

LoadPlugin load

LoadPlugin memory

LoadPlugin ping
<Plugin ping>
	TTL 127
	Interval 30
	AddressFamily "ipv4"
	Host "1.1.1.1"
	Host "9.9.9.9"
</Plugin>

LoadPlugin processes
<Plugin processes>
	Process "nginx"
	Process "dnsmasq"
	Process "AdGuardHome"
	Process "uwsgi"
	Process "tc"
	Process "banip"
</Plugin>

LoadPlugin rrdtool
<Plugin rrdtool>
	DataDir "/opt/rrd"
	RRARows 150
	RRASingle false
	RRATimespan 900
	RRATimespan 1800
	RRATimespan 3600
	RRATimespan 14400
	RRATimespan 28800
	RRATimespan 43200
	RRATimespan 57600
	RRATimespan 86400
	RRATimespan 259200
	RRATimespan 432000
	RRATimespan 604800
	RRATimespan 2678400
</Plugin>

LoadPlugin syslog
<Plugin syslog>
	LogLevel "notice"
	NotifyLevel "OKAY"
</Plugin>

